Adding VIES VAT api
sandwave-io/vat-php pull request #4
Opened 2021-02-03 15:44 UTC by daan-barbiers

2021-02-03 16:33 UTC, markdingemanse commented
src/ViesClient.php (blank_line_after_namespace) looks like there was a validation error. PR looks good to me otherwise

2021-02-05 11:01 UTC, markdingemanse requested changes

2021-02-05 11:01 UTC, markdingemanse commented on src/Vat.php
>      public function validateVatNumber(string $vatNumber, string $countryCode): bool
Could we change the name of this function to validateEuropeanVatNumber

2021-02-05 11:01 UTC, markdingemanse commented on src/Vat.php
>      public function validateVatNumber(string $vatNumber, string $countryCode): bool
the naming atm would suggest i could also verify my 日本  vat number

2021-02-05 11:02 UTC, daan-barbiers commented on src/Vat.php
>      public function validateVatNumber(string $vatNumber, string $countryCode): bool
Yessir!

2021-02-05 12:59 UTC, ThomasRedpanda commented on README.md
> +$vatServcie->validateEuropeanVatNumber("YOURVATNUMBERHERE"); // true
```suggestion
$vatServcie->validateEuropeanVatNumber("YOURVATNUMBERHERE", "COUNTRYCODE"); // true
```

2021-02-05 13:19 UTC, ThomasRedpanda approved these changes

2021-02-05 13:20 UTC, FrontEndCoffee approved these changes
If you add the case for vat number validation without country prefix like we talked about, you can merge this. Great work!

2021-02-05 13:43 UTC, merged